### ISSUE TITLE
Lỗi Music Không Phát Được Âm Thanh

### ISSUE THREAD

**Issue by YuaVN** [thebaoproject/cardinal#4]
https://user-images.githubusercontent.com/95994365/183853255-a4496fec-2687-4b8d-a957-eef4a4df986c.mp4

# Log 
![image](https://user-images.githubusercontent.com/95994365/183853060-796f48f4-5c53-488e-827c-1c553598a83b.png)

**Comment by SpikeVN** [comment]
FFmpeg binary đã bị bỏ từ commit [này](https://github.com/thebaoproject/cardinal/commit/dbd50bff200f496fbcd63efe8db27a566edd0967). Chú phải tự tải FFmpeg, giải nén nó vào trong PATH.

**Comment by YuaVN** [comment]
> 

ok
